catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@0.3.3"
  vite-plus: "0.3.3"

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowedVersions:
    vite: "*"
  allowAny:
    - vite

allowBuilds:
  esbuild: true
