apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-vite-starter-setting
spec:
  forms:
    - group: basic
      label: 基础
      formSchema:
        - $formkit: textarea
          name: custom_footer
          label: 自定义页脚
          value: ""
